"""corrigindo peso atleta

Revision ID: 4868ef81c512
Revises: 422a812ef7d7
Create Date: 2026-01-08 22:45:32.745812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4868ef81c512'
down_revision: Union[str, Sequence[str], None] = '422a812ef7d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('peso', sa.Float(), nullable=False))
    op.drop_column('atletas', 'Peso')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('Peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('atletas', 'peso')
    # ### end Alembic commands ###
